# -*- coding: utf-8 -*-
"""hw1ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5VLU85UsU2RFwlGGaSRwA-SNguLNxh2
"""

#HW1 ex1

#Start function
def startup():
  operator = int(input("Enter your operator type (1-5): "))
  a = float(input("Enter first number: "))
  b = float(input("Enter second number: "))

  calculate(operator, a, b)

#Calculation function
def calculate(operator, a, b):

  while(True):
    if operator == 1:
      operator = '+'
      result = a + b

    if operator == 2:
      operator = '-'
      result = a - b

    if operator == 3:
      operator = '*'
      result = a * b

    if operator == 4:
      operator = "÷"
      result = a / b

    if operator == 5:
      print("Closing...")
      exit(True)
      break

    print(a, operator, b, " = ", result)
    startup()

#Special exit function. I probably won't use it
def exit1():
  while(True):
    if operator == 5:
      exit()

booleanInput = input("Would you like to start? Type y or n")

if booleanInput == "n":
  exit()

elif booleanInput == "y":
  startup()



#a = int(input("Enter your operator type: "))
#
#b = int(input("Enter first number: "))
#c = int(input("Enter second number: "))
#
#if a == 1:
#  print (a + b)
#elif a == 2:
#  print (a - b)
#elif a == 3:
#  print (a * b)
#elif a == 4:
#  print (a / b)
#elif a == 5: