# -*- coding: utf-8 -*-
"""hw1ex2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E33HCuSK1wyb94QnfwGe4cSx5v9MeNjc
"""

#HW 1 exercise 2
a = int(input("First number: "))

b = int(input("Second number: "))

c = input("Enter calculation type: ")

while(True):
  if c == '+':

    print(a, " + ", b, " = ", a + b)

  elif c == '-':
    print(a, " - ", b, " = ", a - b)

  elif c == '*':
    print (a, " * ", b, " = ", a * b)

  elif c == '/':
    print (a, "/", b, " = ", a / b)

  else:
    print("Error.")

  break