# -*- coding: utf-8 -*-
"""hw1ex3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Z3TPhlw-2L6pjfE2wvHQPy6lU01p-PQ
"""

#HW1 excerise 3
list_index = [5,6,7,4,5,6,7,8]
element = 7
i = list_index[0] - 1

while i < element:
  i += 1

  print(i)